<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="3.1.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.9" />
    <PackageReference Include="System.Reflection.Metadata" Version="10.0.9" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\jnUtil\jnUtil.csproj" />
  </ItemGroup>

</Project>
