name: .NET Nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release
  APP_NAME: jnUtil

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Test
      run: dotnet test jnUtilTests/jnUtilTests.csproj --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --verbosity normal --collect "Code coverage"

  publish-nuget:
    runs-on: windows-latest
    needs: build-and-test
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Get version from project file
      id: get_version
      shell: pwsh
      run: |
        $xml = [Xml] (Get-Content "**\${{ env.APP_NAME }}.csproj")
        $version = $xml.Project.PropertyGroup.Version
        echo "Version: $version"
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Pack
      run: dotnet pack ${{ env.APP_NAME }}/${{ env.APP_NAME }}.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --output "$env:RUNNER_TEMP/packages" -p:IncludeSymbols=false
      shell: pwsh

    - name: Publish NuGet Package
      shell: pwsh
      run: |
        $pkgs = Get-ChildItem -Path "$env:RUNNER_TEMP/packages" -Filter *.nupkg
        if (-not $pkgs) { throw "No .nupkg files found" }
        foreach ($pkg in $pkgs) {
          Write-Host "Publishing $($pkg.Name)"
          dotnet nuget push $pkg.FullName --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
        }